//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bussiness
    {
        public int Bussiness_Id { get; set; }
        public string Bussiness_name { get; set; }
        public string summery { get; set; }
        public string phone { get; set; }
        public string Credit { get; set; }
        public string media { get; set; }
        public string b_address { get; set; }
        public int points { get; set; }
        public string photos { get; set; }
        public string userEmail { get; set; }
    
        public virtual User User { get; set; }
        public virtual Treatment Treatment { get; set; }
    }
}
