//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment
    {
        public int treatmentId { get; set; }
        public string Treatment_name { get; set; }
        public string Summary { get; set; }
        public int Treatment_duration { get; set; }
        public int Cost { get; set; }
        public int typeId { get; set; }
        public int Bussiness_Id { get; set; }
    
        public virtual Bussiness Bussiness { get; set; }
    }
}
